### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by fi0** [rhssk/PMW3360DM-T2QU#1]
is it possible to place the sensor in the middle of the board? thank you!

**Comment by rhssk** [comment]
Hi. Sure, it's possible, but I'm not convinced it's necessary. Do you have a good practical reason for these changes?

**Comment by fi0** [comment]
I'm creating a trackball holder. It seems that if the sensor is placed in the center, it's easier to create the 3D model that holds the sensor and trackball together. I'm not sure though.

**Comment by rhssk** [comment]
Implemented in f774e81

**Comment by fi0** [comment]
thank you!!
