### ISSUE TITLE
Files cannot be opened

### ISSUE THREAD

**Issue by Ladniy** [rhssk/PMW3360DM-T2QU#2]
Hello! I have problems with opening KiCad files. When I try to open any of them, I get an error like "Does not appear to be an eeschema file".
Which version of KiCad did you use to design it?

**Comment by rhssk** [comment]
Hi! I used the development version (5.99). Try installing a relatively recent nightly build and give it a go then.

**Comment by Ladniy** [comment]
Okay, i will try later. May I ask you to plot schematic in pdf and send it to me?

**Comment by rhssk** [comment]
[Here you go](https://github.com/rhssk/PMW3360DM-T2QU/files/6103495/board.pdf)

**Comment by Ladniy** [comment]
Thanks!
