### ISSUE TITLE
NCS and QMK 

### ISSUE THREAD

**Issue by GeekAnnoyed** [rhssk/PMW3360DM-T2QU#3]
Hello
I'm really sorry to ask such a noob question 

I'm currently making a QMK dacytal manufom keyboard and I opted for this sensor breakout.

I'm coming to wire it into the RP2040 and I have no idea what the NCS pin does. I can see it in the datasheet 
but when I'm reading the QMK docs for SPI and pmw3360 I'm not seeing anything about it.

any help would absolutely awesome
Richard

**Comment by rhssk** [comment]
Hi Richard!

I'm not familiar with QMK firmware, but from a quick look at their docs it seems like `NCS` is the same as `SS` or slave select. So you probably just need to wire NCS to a free RP2040 pin and then pass it to the [`spi_start`](https://github.com/qmk/qmk_firmware/blob/master/docs/spi_driver.md#bool-spi_startpin_t-slavepin-bool-lsbfirst-uint8_t-mode-uint16_t-divisor) function through the `slavePin` parameter.

Hope that helps. Good luck!

**Comment by GeekAnnoyed** [comment]
Thank you so much,

I suspected it was the case by process of elimination but... didn't want to fry everything.
